$(document).ready(function(){
    $("#baidu").click(function(){
        window.location.href="http://www.baidu.com";
    });
    $("#google").click(function(){
        window.location.href="http://www.google.com";
    });
    $("#translate").click(function(){
        window.location.href="https://translate.google.cn";
    });
    $("#leetcode").click(function(){
        window.location.href="https://leetcode-cn.com/";
    });
    $("#csdn").click(function(){
        window.location.href="https://blog.csdn.net/wangerxiao121223";
    });
    $("#leetcode").click(function(){
        window.location.href="https://leetcode-cn.com/";
    });
    $("#blog").click(function(){
        window.location.href="https://www.cnblogs.com/melodyjerry/";
    });
    $("#github").click(function(){
        window.location.href="https://github.com";
    });
    $("#bilibili").click(function(){
        window.location.href="https://www.bilibili.com";
    });
    $("#youtube").click(function(){
        window.location.href="https://www.youtube.com";
    });
    $("#qqemail").click(function(){
        window.location.href="https://mail.qq.com";
    });
    $("#wyy").click(function(){
        window.location.href="https://music.163.com/";
    });
})